apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mavenwebapp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb      # tells the controller to manage this ingress
    alb.ingress.kubernetes.io/scheme: internet-facing  # or internal
spec:
  rules:
    - host: demo.paytm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mavenwebappsvc
                port:
                  number: 80
